apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce-dev
resources:
  - ../../base
  - namespace.yaml
  # - backend-sealed-secret.yaml     # bỏ comment SAU khi seal cho ecommerce-dev
patches:
  - path: replicas-patch.yaml
  - target: { kind: Ingress, name: ecommerce-ingress }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.k8s.nguyendat.tech
