apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ecommerce-dev
resources:
  - ../../base
  - namespace.yaml
  - hpa.yaml
  # - backend-sealed-secret.yaml
patches:
  - target: { kind: Ingress, name: ecommerce-ingress }
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.k8s.nguyendat.tech
