# Application cho môi trường dev. Apply tay 1 lần (hoặc apply cả thư mục argocd/).
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nguyenmanhdat006/cluster_k8s_argocd
    targetRevision: main
    path: app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
